---
name: Continuous Integration
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Build Native Image
        run: csbt nativeImage
      - name: Run Native Image
        run: |
          echo "Running native image"
          pid=$(csbt nativeImageRun &)
          sleep 5
          kill pid
